blank_issues_enabled: true
contact_links:
  - name: ğŸ’¬ Community Support
    url: https://t.me/winsnip
    about: Join our Telegram group for community support and discussions
  - name: ğŸ¦ Twitter
    url: https://twitter.com/winsnip
    about: Follow us on Twitter for updates and announcements
  - name: ğŸ“§ Email Support
    url: mailto:admin@winsnip.xyz
    about: Contact us directly via email for business inquiries
  - name: ğŸ“š Documentation
    url: https://github.com/winsnip-official/winscan.org/blob/dev/README.md
    about: Read our documentation for guides and tutorials
